export const CHANGE_WRITER_LIST = 'home/change_writer_list'
export const CHANGE_WRITER_LIST_PAGE = 'home/change_writer_list_page'
export const CHANGE_TOPIC_LIST = 'home/change_topic_list'
export const CHANGE_ARTICLE_LIST = 'home/change_article_list'
export const GET_HOME_INFO = 'home/get_home_info'
export const SET_MORE_ARTICLE = 'home/set_more_article'
export const TOGGLE_TOP_SHOW = 'home/toggle_top_show'
